## Configure
projectName=eunoia
groupName=com.lomeone.eunoia
kotlin.code.style=official

## module version
awsPackageVersion=0.0.1
eventCorePackageVersion=0.0.1
exceptionPackageVersion=0.0.3
kotlinUtilVersion=0.0.1
optimizePackageVersion=0.0.1
securityPackageVersion=0.0.1
springEventKafkaPackageVersion=0.0.1
springWebPackageVersion=0.0.1
