## Configure
projectName=eunoia
groupName=com.lomeone.eunoia
kotlin.code.style=official

## module version
awsPackageVersion=0.0.1
eventCorePackageVersion=0.0.1
exceptionPackageVersion=0.0.3
kotlinUtilVersion=0.0.1
optimizePackageVersion=0.0.1
securityPackageVersion=0.0.1
springEventKafkaPackageVersion=0.0.1
springWebPackageVersion=0.0.1

## Root dependencies version
kotlinVersion=2.3.0
kotestVersion=6.0.7
koverVersion=0.9.4
coverallsVersion=1.2.20
sonarqubeVersion=7.2.2.6593

## event-core version
cloudeventsVersion=4.0.1

# event-spring-kafka version
springKafkaVersion=3.2.3

## event-spring-transaction-outbox version
kotlinxSerializationJsonVersion=1.7.2
springBootVersion=3.2.8
springDependencyManagementVersion=1.1.6

## kafka-connect-smt version
shadowVersion=8.3.0
kafkaConnectVersion=3.4.1
kotlinSerializationVersion=1.7.1
slf4jApiVersion=2.0.16

# kotlin-util version
kotlinxSerializationVersion=1.7.3

## spring-web-rest version
springFrameworkVersion=6.2.4

# kotest version
