# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.3.0"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.0.9"
kotlinxCoroutines = "1.10.2"
aws = "1.5.115"
cloudeventsKafka = "4.0.1"
springFramework = "6.2.15"
kotest = "6.0.7"
kover = "0.9.4"
coveralls = "1.2.20"
sonarqube = "7.2.2.6593"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
aws-bom = { module = "aws.sdk.kotlin:bom", version.ref = "aws" }
aws-kms = { module = "aws.sdk.kotlin:kms" }
aws-sts = { module = "aws.sdk.kotlin:sts" }
cloudevents-kafka = { module = "io.cloudevents:cloudevents-kafka", version.ref = "cloudeventsKafka" }
spring-framework-bom = { module = "org.springframework:spring-framework-bom", version.ref = "springFramework"}
spring-framework-web = { module = "org.springframework:spring-web"}
kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }
kotest-property = { module = "io.kotest:kotest-property" }

# Libraries can be bundled together for easier import
[bundles]
kotlinx-ecosystem = ["kotlinx-datetime", "kotlinx-serialization", "kotlinx-coroutines"]
kotest-test-suite = ["kotest-runner-junit5", "kotest-property"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
coveralls = { id = "com.github.nbaztec.coveralls-jacoco", version.ref = "coveralls" }
soraqube = { id = "org.sonarqube", version.ref = "sonarqube" }
