name: Publish package to Github Package

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Publish package
        run: ./gradlew ${{ inputs.module }}:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
