name: Publish exception module to Github Package

on:
  push:
    branches: [main]
    paths:
      - 'exception/**'

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/package-publish.yaml
    with:
      module: 'exception'
