name: Publish kotlin-util module to Github Package

on:
  push:
    branches: [main]
    paths:
      - 'kotlin-util/**'

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/package-publish.yaml
    with:
      module: 'kotlin-util'
