name: Publish spring-web-rest module to Github Package
on:
  push:
    branches: [main]
    paths:
      - 'spring-web-rest/**'

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/package-publish.yaml
    with:
      module: 'spring-web-rest'
